In [1]:
import numpy as np

In [24]:
a = np.array([
    [100,200,150,300],
    [50,60,40,80],
    [300,400,350,500],
    [200,250,220,270],
    [80,90,70,100]
])

In [40]:
#1 Determine the number of dimensions of the array.
a.ndim


2

In [41]:
#3 Calculate the total number of elements in the array.
a.size

20

In [5]:
#4 Find the total memory (in bytes) used by the array.
a.nbytes

160

In [44]:
#5 Add 20 units of stock to all products across all locations.
a+20

array([[120, 220, 170, 320],
       [ 70,  80,  60, 120],
       [320, 420, 370, 520],
       [220, 270, 240, 290],
       [100, 110,  90, 120]])

In [7]:
#6 Deduct 10 units of stock from Product 3 across all locations.
a[2]-10

array([290, 390, 340, 490])

In [8]:
#7 Calculate the percentage of stock available for each product at all locations, assuming the maximum capacity of each location is 1000 units.
max_capacity = 1000
(a/ max_capacity) * 100


array([[10., 20., 15., 30.],
       [ 5.,  6.,  4.,  8.],
       [30., 40., 35., 50.],
       [20., 25., 22., 27.],
       [ 8.,  9.,  7., 10.]])

In [27]:
#8Calculate the total stock of each product across all locations.
np.sum(a,axis = 1)

array([ 750,  230, 1550,  940,  340])

In [28]:
#9 Determine the total stock available in each location.
np.sum(a,axis = 0)

array([ 730, 1000,  830, 1250])

In [29]:
#10 Find the product with the maximum total stock across all locations.
np.max(a,axis = 0)

array([300, 400, 350, 500])

In [42]:
#11 identify the location with the minimum total stock across all products.
np.min(a,axis = 1)

array([100,  40, 300, 200,  70])

In [31]:
#12 Compute the average stock per product across all locations.
np.mean(a,axis = 1)

array([187.5,  57.5, 387.5, 235. ,  85. ])

In [32]:
#13 Retrieve the stock levels of Product 2 across all locations.
a[1]

array([50, 60, 40, 80])

In [33]:
#14 Extract the stock levels for all products in Location 3.
a[:,2]

array([150,  40, 350, 220,  70])

In [34]:
#15 Extract the stock levels of the first 3 products for the first 2 locations.
a[0:3,0:2]

array([[100, 200],
       [ 50,  60],
       [300, 400]])

In [43]:
#16 Slice the stock levels of the last 2 products for the last 2 locations.
a[3:5, 2:4]

array([[220, 270],
       [ 70, 100]])

In [36]:
#17 Identify the stock of Product 5 at Location 3.
stock = a[4,2]
print(stock)

70


In [37]:
#18 Use advanced indexing to find the stock levels of Product 1 at Location 1 and Product 4 at Location 3. 
products = [0, 3]  
locations = [0, 2]  

stock_levels = a[products, locations]

print(stock_levels)

[100 220]


In [38]:
#19 Update the stock of Product 2 at Location 4 to 100 units.
a[1, 3] = 100  
print(a)

[[100 200 150 300]
 [ 50  60  40 100]
 [300 400 350 500]
 [200 250 220 270]
 [ 80  90  70 100]]


In [39]:
#20Double the stock of all products at Location 2 (column 2).
a[1,1]*2

np.int64(120)